version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: technical-assessment-db
    environment:
      POSTGRES_DB: ${DB_NAME:-technical_assessment}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: technical-assessment-api
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/uploads

volumes:
  postgres_data:
  uploads_data:
