name: docker-build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./dockerfile
          push: false
          load: true
          tags: technical-assessment:ci-test

      - name: Export Docker image
        run: |
          docker save technical-assessment:ci-test -o technical-assessment.tar

      - name: Upload image artifact
        uses: actions/upload-artifact@v4
        with:
          name: technical-assessment-image
          path: technical-assessment.tar
          retention-days: 7
